version: 2.1

machine:
  services:
    - mongodb
jobs:
  build-and-test:
    working_directory: ~/habit-tracker-backend
    docker:
      - image: circleci/node:12
      - image: circleci/mongo:latest
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
    environment:
      PORT: 3000
      MONGO_URI: "mongodb://127.0.0.1:27017/habit_db"
      NODE_ENV: "dev"
      PASSPORT_SECRET: "secret"
workflows:
  build-and-test:
    jobs:
      - build-and-test
