version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
    environment:
      PORT: 3000
      MONGO_URI: "mongodb://127.0.0.1:27017/habit_db"
      NODE_ENV: "dev"
      PASSPORT_SECRET: "secret"
workflows:
  build-and-test:
    jobs:
      - build-and-test
