version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/node:12
      - image: circleci/mongo:latest
    working_directory: ~/habit-tracker-backend
    steps:
      - checkout
      - run:
        name: Update npm
        command: 'sudo npm install -g npm@latest'
    - restore_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
    - run:
        name: Install npm
        command: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
        paths:
          - node_modules
    - run:
        name: Test
        command: npm test
    environment:
      PORT: 3000
      MONGO_URI: "mongodb://127.0.0.1:27017/habit_db"
      NODE_ENV: "dev"
      PASSPORT_SECRET: "secret"
workflows:
  build-and-test:
    jobs:
      - build-and-test
